export const colorByType = {
  normal: "bg-secondary",
  fighting: "bg-danger",
  flying: "bg-primary",
  poison: "bg-dark",
  ground: "bg-warning",
  rock: "bg-warning",
  bug: "bg-success",
  ghost: "bg-secondary",
  steel: "bg-light",
  fire: "bg-danger",
  water: "bg-primary",
  grass: "bg-success",
  electric: "bg-warning",
  psychic: "bg-danger",
  ice: "bg-info",
  dragon: "bg-primary",
  dark: "bg-dark",
  fairy: "bg-light",
  unknown: "",
  shadow: "",
};
